/** Pure text contract shared by generation, the script editor, and exports. */
export const NARRATION_WORDS_PER_SECOND = 2.35;
const SENTENCE_END = /[.!?。！？][”’"'»）)]*$/u;
const ABBREVIATION = /\b(?:Mr|Mrs|Ms|Dr|Prof|St|Sr|Jr|Mt|No|vs|approx|sq|ft)\.$/iu;
const EDITOR_COPY = /(?:continue the property tour through .{0,120}using only details visible|review and edit this generated card|generated as a draft\. edit the details|could not be classified confidently|review them before assigning a specific room label|use this (?:action )?card (?:as|to)|generated by the livingwiki wizard)/iu;

export function normalizeNarrationText(value: string): string {
  return value.replace(/\s+/gu, ' ').trim();
}

export function narrationSentences(value: string): string[] {
  const text = normalizeNarrationText(value);
  if (!text) return [];
  const pieces = typeof Intl.Segmenter === 'function'
    ? Array.from(new Intl.Segmenter(undefined, { granularity: 'sentence' }).segment(text), ({ segment }) => segment.trim())
    : text.split(/(?<=[.!?。！？][”’"']?)\s+(?=[\p{Lu}\p{N}“"'])|(?<=[。！？])(?=\S)/u);
  const sentences: string[] = [];
  for (const piece of pieces.filter(Boolean)) {
    if (sentences.length && ABBREVIATION.test(sentences[sentences.length - 1])) {
      sentences[sentences.length - 1] += ` ${piece}`;
    } else sentences.push(piece);
  }
  return sentences;
}

export function containsEditorCopy(value: string): boolean {
  return EDITOR_COPY.test(value);
}

/** Conservative known fragments, not a grammar checker for arbitrary authored text. */
export function hasDanglingNarration(value: string): boolean {
  return narrationSentences(value).some((sentence) =>
    /\b(?:with|and|or|but|because|including|such as|features a|offers a|shown staged with|in the|to the|of the|for the)\s*[.!?…]*[”’"']*$/iu.test(sentence));
}

export function isFinishedNarration(value: string): boolean {
  const text = normalizeNarrationText(value);
  return !!text && SENTENCE_END.test(text) && !hasDanglingNarration(text) && !containsEditorCopy(text);
}

/** A budget is soft: a complete first sentence is preferable to a severed clause. */
export function fitNarrationToWords(value: string, maxWords: number, maxCharacters = 3600): string {
  const selected: string[] = [];
  let words = 0;
  for (const part of narrationSentences(value)) {
    if (!isFinishedNarration(part)) continue;
    const count = part.split(/\s+/u).length;
    if (selected.length && words + count > maxWords) break;
    if ([...selected, part].join(' ').length > maxCharacters) break;
    selected.push(part);
    words += count;
  }
  const result = selected.join(' ');
  if (result && !preservesNarrationQualifications(result, value)) {
    const qualified = shortenNarrationSentences(value, Math.min(3, selected.length));
    if (qualified.length <= maxCharacters) return qualified;
    return '';
  }
  return result;
}

/** Compact display text may elide; spoken scripts must use whole sentences. */
export function narrationSummary(value: string, max = 160): string {
  const text = normalizeNarrationText(value);
  if (text.length <= max) return text;
  const complete = fitNarrationToWords(text, Infinity, max);
  if (complete) return complete;
  const boundary = text.lastIndexOf(' ', max - 1);
  return `${text.slice(0, boundary > 0 ? boundary : max - 1).replace(/[,:;]$/u, '')}…`;
}

const NUMBER_WORDS: Record<string, string> = {
  zero: '0', one: '1', two: '2', three: '3', four: '4', five: '5', six: '6', seven: '7',
  eight: '8', nine: '9', ten: '10', eleven: '11', twelve: '12', thirteen: '13', fourteen: '14',
  fifteen: '15', sixteen: '16', seventeen: '17', eighteen: '18', nineteen: '19', twenty: '20',
};

export function narrationNumberTokens(value: string): string[] {
  const normalized = value.toLowerCase().replace(/\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty)\b/gu,
    (word) => NUMBER_WORDS[word]);
  return (normalized.match(/(?:[$€£]\s*)?\d[\d,.]*(?:\s*%|\s*(?:sq\.?\s*ft|square feet|bedrooms?|bathrooms?|beds?|baths?|acres?|miles?|minutes?))?/giu) ?? [])
    .map((token) => token.replace(/,/gu, '').replace(/\s+/gu, '').replace(/[.]+$/u, ''));
}

export function introducesNarrationNumbers(candidate: string, source: string): boolean {
  const approved = new Set(narrationNumberTokens(source));
  return narrationNumberTokens(candidate).some((token) => !approved.has(token));
}

// Removing one of these qualifications can strengthen a factual claim.
const QUALIFICATIONS = [
  /\b(?:not included|does not convey|may not be included|staging only|virtually staged|unfurnished)\b/iu,
  /\b(?:subject to|pending|under contract|not guaranteed|cannot guarantee)\b/iu,
  /\b(?:estimated|approximately|approx\.|unverified|not verified|may vary)\b/iu,
  /\b(?:not|no|never|without|unless|except|excluding|subject to|may|might|could|cannot|can['’]t|doesn['’]t|don['’]t|isn['’]t|aren['’]t|won['’]t)\b/iu,
  /\b(?:pas|sans|sauf|environ|estim[ée]e?s?|sous réserve|non inclus|non vérifié|peut|pourrait)\b/iu,
  /(?:含まれ(?:てい)?ません|未確認|概算|推定|場合があります|保証されません|ではありません)/u,
];

function qualificationKey(value: string): string {
  return normalizeNarrationText(value.toLowerCase().replace(/[\p{P}\p{S}]/gu, ' '));
}

function qualificationSentences(value: string): string[] {
  return narrationSentences(value).filter((sentence) => !containsEditorCopy(sentence)
    && QUALIFICATIONS.some((pattern) => pattern.test(sentence)));
}

export function preservesNarrationQualifications(candidate: string, source: string): boolean {
  // Require every qualified claim, not merely one word from the same category.
  // A conservative fallback is safer than accepting a changed inclusion or denial.
  const key = qualificationKey(candidate);
  return qualificationSentences(source).every((sentence) => key.includes(qualificationKey(sentence)));
}

export function shortenNarrationSentences(value: string, targetSentences: number): string {
  const text = normalizeNarrationText(value);
  const target = Math.max(1, Math.min(3, Math.trunc(targetSentences) || 1));
  const all = narrationSentences(text);
  if (all.length <= target && !hasDanglingNarration(text) && !containsEditorCopy(text)) return text;
  const complete = all.filter(isFinishedNarration);
  // Preserve authored material when no safe complete sentence is available.
  if (!complete.length) return text;
  const selected = complete.slice(0, target);
  const qualifiers = qualificationSentences(complete.slice(target).join(' ')).filter((sentence) =>
    !qualificationKey(selected.join(' ')).includes(qualificationKey(sentence)));
  if (qualifiers.length) {
    const last = selected.pop()!;
    const cjk = /[。！？]/u.test(last);
    selected.push([last, ...qualifiers].map((part) => part.replace(/[.!?。！？][”’"'»）)]*$/u, '')).join(cjk ? '；' : '; ') + (cjk ? '。' : '.'));
  }
  const result = selected.join(' ');
  return preservesNarrationQualifications(result, text) ? result : text;
}

export type NarrationAdjustmentCard = { cardId: string; narration: string; sourceNarration?: string };
export type NarrationAdjustment = { cardId: string; narration: string };

export function adjustNarrationSentences(card: NarrationAdjustmentCard, target: number): string {
  const current = normalizeNarrationText(card.narration);
  const source = normalizeNarrationText(card.sourceNarration || current);
  const expand = narrationSentences(current).length < target && narrationSentences(source).length > narrationSentences(current).length;
  return shortenNarrationSentences(expand ? source : current, target);
}

export function normalizeNarrationAdjustments(
  cards: readonly NarrationAdjustmentCard[], results: readonly NarrationAdjustment[], target: number,
): NarrationAdjustment[] {
  const byId = new Map<string, string>();
  const duplicateIds = new Set<string>();
  for (const result of results) {
    if (!result || typeof result.cardId !== 'string' || typeof result.narration !== 'string') continue;
    if (byId.has(result.cardId)) duplicateIds.add(result.cardId);
    byId.set(result.cardId, typeof result.narration === 'string' ? normalizeNarrationText(result.narration) : '');
  }
  return cards.map((card) => {
    const candidate = byId.get(card.cardId) || '';
    const source = normalizeNarrationText(card.sourceNarration || card.narration);
    const shortened = shortenNarrationSentences(candidate, target);
    const acceptable = !duplicateIds.has(card.cardId)
      && isFinishedNarration(candidate) && isFinishedNarration(shortened)
      && !introducesNarrationNumbers(candidate, source)
      && preservesNarrationQualifications(shortened, source);
    return { cardId: card.cardId, narration: acceptable ? shortened : adjustNarrationSentences(card, target) };
  });
}
