// Shared localized copy for conditional template labels.
export const offGridCopy = {
  unmuteMic: $localize`Unmute mic`,
  muteMic: $localize`Mute mic`,
  preparingYourVideoAndCover: $localize`Preparing your video and cover…`,
  uploading: $localize`Uploading · `,
  addingPinTalk: $localize`Adding PinTalk…`,
  addThisPinTalk: $localize`Add this PinTalk`,
  refineYourGem: $localize`Refine your gem`,
  markAGem: $localize`Mark a gem`,
  findingLocation: $localize`Finding location…`,
  useMyLocation: $localize`Use my location`,
  exactPointConfirmed: $localize`Exact point confirmed`,
  checkYourExactPoint: $localize`Check your exact point`,
  confirmed: $localize`✓ Confirmed`,
  confirmThisPoint: $localize`Confirm this point`,
  changePhoto: $localize`Change photo`,
  uploadPhoto: $localize`Upload photo`,
  preparingYourPhoto: $localize`Preparing your photo…`,
  uploadingPhoto: $localize`Uploading photo · `,
  recordOrUpload: $localize`Record or upload`,
  addingAPinTalkPlacesItOn: $localize`Adding a PinTalk places it on your currently public gem.`,
  yourPinTalkStaysPrivateUntilYou: $localize`Your PinTalk stays private until you publish this gem.`,
  yourGemIsPrivateByDefault: $localize`Your gem is private by default. You can publish it any time.`,
  publishingSharesTheExactCoordinatesPhoto: $localize`Publishing shares the exact coordinates, photo and approved PinTalks. You can make the gem private again.`,
  continueToStory: $localize`Continue to story`,
  reviewGem: $localize`Review gem`,
  saving: $localize`Saving…`,
  publishGem: $localize`Publish gem`,
  savePrivateGem: $localize`Save private gem`,
  findingGems: $localize`Finding gems…`,
  searchThisArea: $localize`Search this area`,
  draft: $localize`Draft`,
  setLocation: $localize`Set location`,
  private: $localize`Private`,
  offGrid: $localize`Off Grid`,
  confirmAMapPoint: $localize`Confirm a map point`,
  aGemWaitingForItsStory: $localize`A gem waiting for its story.`,
  yourNextGemStartsHere: $localize`Your next gem starts here`,
  keepAFewGemsForLater: $localize`Keep a few gems for later`,
  noGemsFound: $localize`No gems found`,
  saveAPlaceYouWantTo: $localize`Save a place you want to come back to.`,
  tryAnotherSearchOrMarkA: $localize`Try another search, or mark a place you love.`,
  findingMoreGems: $localize`Finding more gems…`,
  discoverMore: $localize`Discover more`,
  privateGem: $localize`Private gem`,
  offGridGem: $localize`Off Grid gem`,
  close: $localize`Close`,
  addPinTalk: $localize`Add PinTalk`,
  yourPinTalkStaysPrivateWithThis: $localize`Your PinTalk stays private with this gem.`,
  addingThisPinTalkMakesItVisible: $localize`Adding this PinTalk makes it visible on your public gem.`,
  yourPinTalkWillBePrivateUntil: $localize`Your PinTalk will be private until the owner approves it.`,
  featuredPinTalk: $localize`Featured PinTalk`,
  pintalk: $localize`PinTalk`,
  awaitingApproval: $localize`Awaiting approval`,
  shareThisGem: $localize`Share this gem`,
  letSGo: $localize`Let’s go`,
  unsave: $localize`Unsave `,
  save: $localize`Save `,
  unsaveThisGem: $localize`Unsave this gem`,
  saveThisGem: $localize`Save this gem`,
  pintalkBy: $localize`PinTalk by `,
  directionsToThisGem: $localize`Directions to this gem`,
  place: $localize`Place`,
  story: $localize`Story`,
  review: $localize`Review`,
};
